### ISSUE TITLE
Request: Offline mode

### ISSUE THREAD

**Issue by Hunanbean** [egradman/scales-chords#5]
I keep Obsidian offline, but i do like this plugin.
I am simply requesting an offline mode. 
I understand that it is probably out of the scope of this project. If so, please close this issue.

Thank you

**Comment by egradman** [comment]
On it's face, this idea sounds crazy because I'm using a service that just serves up images on demand.  

But, you might be able to achieve this on your own, depending on the reasons for which you keep Obsidian offline.  My first thought is that if you install a cacheing proxy like [SquidMan](https://squidman.net/squidman/) you can fetch the images when you're online, then still access them when you're offline.

That said, I'm going to close this issue because it's totally out of scope of this project!  Good luck!

**Comment by Hunanbean** [comment]
Thank you for the insight! Squid is part of the official repositories of Manjaro, so i installed it. Time to learn something new
